import type { Config } from '@netlify/functions'
import OpenAI from 'openai'
import * as Astronomy from 'astronomy-engine'
type Input={name:string;birthDate:string;birthTime:string;utcOffset:string;birthPlace:string;timeAccuracy?:string;focus?:string[]}
const signs=['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces']
const nakshatras=['Ashwini','Bharani','Krittika','Rohini','Mrigashira','Ardra','Punarvasu','Pushya','Ashlesha','Magha','Purva Phalguni','Uttara Phalguni','Hasta','Chitra','Swati','Vishakha','Anuradha','Jyeshtha','Mula','Purva Ashadha','Uttara Ashadha','Shravana','Dhanishta','Shatabhisha','Purva Bhadrapada','Uttara Bhadrapada','Revati']
const bodies:[string,Astronomy.Body][]=[['Sun',Astronomy.Body.Sun],['Moon',Astronomy.Body.Moon],['Mercury',Astronomy.Body.Mercury],['Venus',Astronomy.Body.Venus],['Mars',Astronomy.Body.Mars],['Jupiter',Astronomy.Body.Jupiter],['Saturn',Astronomy.Body.Saturn]]
function longitude(body:Astronomy.Body,date:Date){const v=Astronomy.GeoVector(body,date,true),e=Astronomy.Ecliptic(v),years=(date.getTime()-Date.UTC(2000,0,1,12))/31557600000;return(e.elon-(23.85675+years*.01397)+360)%360}
function placement(planet:string,lon:number){return{planet,sign:signs[Math.floor(lon/30)],degree:Number((lon%30).toFixed(2))}}
export default async(req:Request)=>{if(req.method!=='POST')return Response.json({error:'Method not allowed'},{status:405});try{const input=await req.json() as Input;if(!input.name?.trim()||!input.birthDate||!input.birthTime||!input.utcOffset||!input.birthPlace?.trim())return Response.json({error:'Please complete every required birth detail.'},{status:400});const date=new Date(`${input.birthDate}T${input.birthTime}:00${input.utcOffset}`);if(Number.isNaN(date.getTime())||date>new Date())return Response.json({error:'Enter a valid birth date and time.'},{status:400});const chart=bodies.map(([name,body])=>placement(name,longitude(body,date)));const centuries=(date.getTime()-Date.UTC(2000,0,1,12))/3155760000000,years=centuries*100,ayanamsa=23.85675+years*.01397,rahuLon=(125.04452-1934.136261*centuries-ayanamsa+720)%360;chart.push(placement('Rahu',rahuLon),placement('Ketu',(rahuLon+180)%360));const moon=chart.find(p=>p.planet==='Moon')!,moonLon=signs.indexOf(moon.sign)*30+moon.degree,n=Math.floor(moonLon/(360/27));const computed={system:'Sidereal zodiac; approximate Lahiri ayanamsa',moonSign:moon.sign,sunSign:chart[0].sign,nakshatra:nakshatras[n],pada:Math.floor((moonLon%(360/27))/(360/108))+1,planets:chart};const client=new OpenAI();const response=await client.responses.create({model:'gpt-5.2',input:[{role:'system',content:'You are a careful Vedic astrology guide. Interpret only supplied computed placements. Never invent ascendant, houses, dashas, yogas, doshas, events, or guarantees. Distinguish calculation from reflection. Avoid medical, legal, or financial certainty. Return valid JSON only.'},{role:'user',content:JSON.stringify({client:{name:input.name,birthPlace:input.birthPlace,timeAccuracy:input.timeAccuracy,focus:input.focus?.filter(Boolean)},computed,request:'Return JSON: overview string; themes array of {title,body}; focusGuidance array of {question,reflection,action}; note string. Ground claims in supplied placements.'})}],text:{format:{type:'json_object'}},max_output_tokens:2200});return Response.json({computed,reading:JSON.parse(response.output_text)})}catch(error){console.error('Reading generation failed');return Response.json({error:'The reading could not be created right now. Please try again.'},{status:500})}}
export const config:Config={path:'/api/reading',method:'POST'}
